import type { StudentResult } from "./types";

export const sampleData: { [key: string]: StudentResult } = {
  "1NH23CS038": {
    usn: "1NH23CS038",
    name: "BALAJI GS",
    semester: "Semester 3",
    parentName: "SHANKAR G",
    photoUrl:
      "https://res.cloudinary.com/dam5fqx2x/image/upload/v1740160901/bkud6esqhnkhg1rvsqnh.jpg",
    examYear: "2024-25",
    date: "Feb 16 2025",
    courses: [
      {
        sNo: 1,
        courseCode: "22MAD21",
        courseName: "MATHEMATICAL FOUNDATION FOR COMPUTING SCIENCES",
        credits: 3.0,
        grade: "D",
        gpa: 6.0,
      },
      {
        sNo: 2,
        courseCode: "22CSE32",
        courseName: "DIGITAL LOGIC DESIGN",
        credits: 3.0,
        grade: "D",
        gpa: 5.0,
      },
      {
        sNo: 3,
        courseCode: "22CSE33",
        courseName: "PROBLEM SOLVING USING DATA STRUCTURES",
        credits: 3.0,
        grade: "D",
        gpa: 4.0,
      },
      {
        sNo: 4,
        courseCode: "22CSE341",
        courseName: "LINUX SYSTEM PROGRAMMING",
        credits: 3.0,
        grade: "D",
        gpa: 3.0,
      },
      {
        sNo: 5,
        courseCode: "22CSE351",
        courseName: "WEB DESIGN TECHNOLOGIES",
        credits: 1.0,
        grade: "D",
        gpa: 2.0,
      },
      {
        sNo: 6,
        courseCode: "22BID26",
        courseName: "BIO INSPIRED DESIGN AND INNOVATION",
        credits: 3.0,
        grade: "D",
        gpa: 5.0,
      },
      {
        sNo: 7,
        courseCode: "22SCR37",
        courseName: "SOCIAL CONNECT AND RESPONSIBILITY",
        credits: 1.0,
        grade: "O",
        gpa: 10.0,
      },
      {
        sNo: 8,
        courseCode: "22CSL32",
        courseName: "DIGITAL LOGIC DESIGN LAB",
        credits: 1.0,
        grade: "C",
        gpa: 5.0,
      },
      {
        sNo: 9,
        courseCode: "22CSL33",
        courseName: "PROBLEM SOLVING USING DATA STRUCTURES LAB",
        credits: 1.0,
        grade: "B+",
        gpa: 7.0,
      },
      {
        sNo: 10,
        courseCode: "22NSS30",
        courseName: "NATIONAL SERVICE SCHEME",
        credits: 0.0,
        grade: "PP",
        gpa: 0.0,
      },
    ],
    totalCredits: 19,
    sgpa: 5.3,
    cgpa: 6.14,
  },
};
